services:
  express:
    container_name: lambda-web-adapter-express
    image: lambda-web-adapter-express:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      # 3000番ポートをコンテナ側の8080番ポートにマッピングして公開（Lambda Web Adapterのデフォルトポートは8080）
      - "3000:8080"
    tty: true
